# Generated by Django 6.0.1 on 2026-01-23 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la campaña')),
                ('subject', models.CharField(max_length=300, verbose_name='Asunto del correo')),
                ('message', models.TextField(blank=True, verbose_name='Mensaje personalizado')),
                ('excel_file', models.FileField(upload_to='campaigns/', verbose_name='Archivo Excel')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='draft', max_length=20, verbose_name='Estado')),
                ('total_recipients', models.IntegerField(default=0, verbose_name='Total de destinatarios')),
                ('sent_count', models.IntegerField(default=0, verbose_name='Correos enviados')),
                ('failed_count', models.IntegerField(default=0, verbose_name='Correos fallidos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
            ],
            options={
                'verbose_name': 'Campaña de correo',
                'verbose_name_plural': 'Campañas de correo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('certificate_link', models.URLField(max_length=500, verbose_name='Link del certificado')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='correo.emailcampaign', verbose_name='Campaña')),
            ],
            options={
                'verbose_name': 'Destinatario',
                'verbose_name_plural': 'Destinatarios',
                'ordering': ['full_name'],
            },
        ),
    ]
