# Generated by Django 6.0.1 on 2026-01-24 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correo', '0001_initial'),
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcampaign',
            name='excel_file',
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='curso.curso', verbose_name='Curso Asociado'),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='message',
            field=models.TextField(blank=True, verbose_name='Mensaje personalizado (HTML)'),
        ),
        migrations.AlterField(
            model_name='emailrecipient',
            name='certificate_link',
            field=models.URLField(max_length=500, verbose_name='Link del portal'),
        ),
    ]
