# Generated by Django 6.0.1 on 2026-01-27 00:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correo', '0002_remove_emailcampaign_excel_file_emailcampaign_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDailyLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, unique=True, verbose_name='Fecha')),
                ('count', models.IntegerField(default=0, verbose_name='Correos enviados')),
            ],
            options={
                'verbose_name': 'Límite diario de correos',
                'verbose_name_plural': 'Límites diarios de correos',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de tarea Celery'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='current_batch',
            field=models.IntegerField(default=0, help_text='Número del lote que se está procesando actualmente', verbose_name='Lote actual'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='progress',
            field=models.IntegerField(default=0, help_text='Porcentaje de progreso de 0 a 100', verbose_name='Progreso (%)'),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='Estado'),
        ),
    ]
