# Generated by Django 6.0.1 on 2026-01-30 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificado', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='uuid_validacion',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='incluir_qr',
        ),
    ]
