# Generated by Django 6.0.1 on 2026-01-30 00:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificado', '0002_remove_certificado_uuid_validacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='uuid_validacion',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True, verbose_name='UUID de Validación'),
        ),
        migrations.AddField(
            model_name='evento',
            name='incluir_qr',
            field=models.BooleanField(default=False, help_text='Si se activa, se estampará un código QR único en cada certificado generado.', verbose_name='Incluir QR de Seguridad'),
        ),
    ]
