# Generated by Django 6.0.1 on 2026-02-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificado', '0003_certificado_uuid_validacion_evento_incluir_qr'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='certificado',
            name='certificado_evento__16fca3_idx',
        ),
        migrations.AddIndex(
            model_name='certificado',
            index=models.Index(fields=['estudiante', 'estado'], name='certificado_estudia_f659fb_idx'),
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='evento',
        ),
    ]
