# Generated by Django 6.0.1 on 2026-01-24 01:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del curso')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('no_disponible', 'No Disponible')], default='disponible', max_length=20, verbose_name='Estado')),
                ('archivo_estudiantes', models.FileField(help_text='Subir archivo con columnas: Nombres y Apellidos completos, Cedula, Correo electronico', upload_to='cursos/estudiantes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls'])], verbose_name='Archivo de Estudiantes (Excel)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la plantilla')),
                ('archivo', models.FileField(upload_to='plantillas_certificados/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpg', 'jpeg'])], verbose_name='Archivo de plantilla')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Plantilla de Certificado',
                'verbose_name_plural': 'Plantillas de Certificados',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=300, verbose_name='Nombres y Apellidos completos')),
                ('cedula', models.CharField(max_length=20, verbose_name='Cédula')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='curso.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['nombre_completo'],
                'unique_together': {('curso', 'cedula')},
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='plantilla_certificado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curso.plantillacertificado', verbose_name='Plantilla de Certificado por defecto'),
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_generado', models.FileField(blank=True, null=True, upload_to='certificados_generados/', verbose_name='Certificado Generado')),
                ('codigo_verificacion', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de Verificación')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de generación')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='curso.estudiante', verbose_name='Estudiante')),
                ('plantilla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curso.plantillacertificado', verbose_name='Plantilla utilizada')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
