# Generated by Django 6.0.1 on 2026-01-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estudiante',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cedula',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Cédula'),
        ),
        migrations.AddIndex(
            model_name='estudiante',
            index=models.Index(fields=['curso', 'cedula'], name='curso_estud_curso_i_64f30b_idx'),
        ),
        migrations.AddIndex(
            model_name='estudiante',
            index=models.Index(fields=['cedula'], name='curso_estud_cedula_da8638_idx'),
        ),
        migrations.AddConstraint(
            model_name='estudiante',
            constraint=models.UniqueConstraint(fields=('curso', 'cedula'), name='unique_estudiante_curso'),
        ),
    ]
