# Generated by Django 6.0.1 on 2026-01-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0009_certificado_access_count_certificado_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='generation_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='curso',
            name='generation_status',
            field=models.CharField(choices=[('idle', 'Inactivo'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='idle', max_length=20),
        ),
        migrations.AddField(
            model_name='curso',
            name='generation_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
